# Generated by Django 5.2.17 on 2026-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaftMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64, unique=True)),
                ('current_term', models.BigIntegerField(default=0)),
                ('voted_for', models.CharField(blank=True, max_length=64, null=True)),
                ('snapshot_index', models.BigIntegerField(default=0)),
                ('snapshot_term', models.BigIntegerField(default=0)),
                ('last_applied', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'raft_meta',
            },
        ),
        migrations.CreateModel(
            name='RaftLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('log_index', models.BigIntegerField()),
                ('term', models.BigIntegerField()),
                ('command', models.TextField()),
                ('username', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'raft_log',
                'unique_together': {('node_id', 'log_index')},
            },
        ),
    ]
