# Generated by Django 5.2.17 on 2026-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raftlogentry',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='raftmeta',
            name='snapshot_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
