# Generated by Django 5.2.17 on 2026-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('last_seq', models.BigIntegerField()),
                ('result', models.TextField()),
                ('last_index', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'client_sessions',
            },
        ),
        migrations.AddField(
            model_name='cacheentry',
            name='expire_at',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
